services:
  backend-java:
    build: ./backend-java
    container_name: ecg-backend-java
    ports:
      - "8081:8080"
    depends_on:
      - inference-service
    networks:
      - ecg-network

  inference-service:
    build: ./inference-service
    container_name: ecg-inference-service
    ports:
      - "5001:5000"
    networks:
      - ecg-network

networks:
  ecg-network:
    driver: bridge
